version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

filter-release: &filter-release
  filters:
    tags:
      only: /^release-202[\d-]+/
    branches:
      ignore: /.*/

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  terraform: circleci/terraform@3.2.1
  gh: circleci/github-cli@1.0
  slack: circleci/slack@4.3.0
  tariff: trade-tariff/trade-tariff-ci-orb@0

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.5.5
    resource_class: small
    working_directory: "/tmp/terraform"
    environment:
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1

  python:
    docker:
      - image: cimg/python:3.11.2
    resource_class: small

jobs:
  lint:
    executor: python
    steps:
      - checkout
      - run:
          name: install flake8
          command: pip install flake8==5.0.4
      - run:
          name: run flake8
          command: flake8 .

  test:
    executor: python
    environment:
      SPACY_DICTIONARY: en_core_web_sm
    steps:
      - checkout
      - restore_cache:
          key: deps-1.0.0-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/test.txt" }}
      - run:
          name: "Setup environment"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
            python3 -m spacy download $SPACY_DICTIONARY
      - save_cache:
          key: deps-1.0.0-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: "Run tests"
          command: |
            . venv/bin/activate
            pytest

  coverage:
    executor: python
    environment:
      SPACY_DICTIONARY: en_core_web_sm
    steps:
      - checkout
      - restore_cache:
          key: deps-1.0.0-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/test.txt" }}
      - run:
          name: "Setup environment"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
            python3 -m spacy download $SPACY_DICTIONARY
      - save_cache:
          key: deps-1.0.0-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          name: "Run tests"
          command: |
            . venv/bin/activate
            pytest --cov --cov-fail-under 92

  write-docker-tag:
    parameters:
      environment:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "docker_tag = \"$(git rev-parse --short HEAD)\"" >> terraform/config_<< parameters.environment >>.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - terraform/

  fmt-validate-terraform:
    executor: terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/fmt:
          path: terraform/
      - terraform/validate:
          path: terraform/

  plan-terraform:
    executor: terraform
    environment:
      TF_CLI_ARGS: "-lock=false"
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/plan:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
          var_file: config_<< parameters.environment >>.tfvars

  apply-terraform:
    executor: terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/apply:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
          var_file: config_<< parameters.environment >>.tfvars
          lock-timeout: 5m
      - run:
          name: Add curl
          command: apk --no-cache add curl jq
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deployments
          event: pass
          template: basic_success_1

  notify-production-deployment:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - tariff/notify-production-release:
          app-name: Search Query Parser
          slack-channel: trade_tariff
          release-tag: $CIRCLE_TAG
workflows:
  version: 2

  deploy-to-development:
    jobs:
      - write-docker-tag:
          name: write-docker-tag-dev
          environment: development
          <<: *filter-not-main

      - lint:
          <<: *filter-not-main

      - test:
          context: trade-tariff-notifications
          <<: *filter-not-main

      - coverage:
          context: trade-tariff-testing
          <<: *filter-not-main

      - fmt-validate-terraform:
          name: fmt-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          <<: *filter-not-main

      - plan-terraform:
          name: plan-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          requires:
            - write-docker-tag-dev
            - fmt-terraform-dev
          <<: *filter-not-main

      - tariff/build-and-push:
          name: build-and-push-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          image_name: tariff-search-query-parser
          ssm_parameter: "/development/SEARCH_QUERY_PARSER_ECR_URL"
          <<: *filter-not-main

      - apply-terraform:
          name: apply-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          requires:
            - test
            - plan-terraform-dev
            - build-and-push-dev
          <<: *filter-not-main

      - tariff/smoketests:
          name: smoketest-dev
          context: trade-tariff-testing
          url: https://dev.trade-tariff.service.gov.uk
          yarn_run: dev-tariff-search-query-parser-smoketests
          requires:
            - apply-terraform-dev
          <<: *filter-not-main

  deploy-to-staging:
    jobs:
      - write-docker-tag:
          name: write-docker-tag-staging
          environment: staging

      - plan-terraform:
          name: plan-terraform-staging
          context: trade-tariff-terraform-aws-staging
          environment: staging
          requires:
            - write-docker-tag-staging
          <<: *filter-not-main

      - tariff/build-and-push:
          name: build-and-push-live
          context: trade-tariff-terraform-aws-staging
          environment: staging
          image_name: tariff-search-query-parser
          ssm_parameter: "/staging/SEARCH_QUERY_PARSER_ECR_URL"
          <<: *filter-main

      - apply-terraform:
          name: apply-terraform-staging
          context: trade-tariff-terraform-aws-staging
          environment: staging
          requires:
            - write-docker-tag-staging
            - plan-terraform-staging
            - build-and-push-live
          <<: *filter-main

      - tariff/smoketests:
          name: smoketest-staging
          context: trade-tariff-testing
          url: https://staging.trade-tariff.service.gov.uk
          yarn_run: staging-tariff-duty-calculator-smoketests
          requires:
            - apply-terraform-staging
          <<: *filter-main

  deploy-to-production:
    jobs:
      - write-docker-tag:
          name: write-docker-tag-prod
          environment: production

      - plan-terraform:
          name: plan-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          requires:
            - write-docker-tag-prod
          <<: *filter-not-main

      - promote-to-production?:
          type: approval
          <<: *filter-main

      - tariff/create-production-release:
          context: trade-tariff-releases
          image-name: tariff-search-query-parser-production
          requires:
            - promote-to-production?
          <<: *filter-main

      - write-docker-tag:
          name: write-docker-tag-prod-release
          environment: production
          <<: *filter-release

      - apply-terraform:
          name: apply-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          requires:
            - write-docker-tag-prod-release
          <<: *filter-release

      - notify-production-deployment:
          context: trade-tariff-releases
          requires:
            - apply-terraform-prod
          <<: *filter-release
